### ISSUE TITLE
Flag to <Form /> to disable the form and all elements

### ISSUE THREAD

**Issue by m4rw3r** [crossroads-loyalty-solutions/formaggio#5]
Currently there is no way to disable any attempts to modify or submit the form again when the application is processing something (eg. previous submission).

Add a `disabled` flag to `<Form />` which will disable the submit-functionality (ie. bail-out of `onSubmit` before it even sets `submitted`) and any ability to edit the data in the form (ie. prevent `onChange`), as well as provide this `disabled` flag in `InputProps` from `useFormField`.

**Comment by peterasplund** [comment]
A disabled fieldset in the form would solve this problem natively. Closing this one.
